Coconut Oil: 5
Eggs: 5
Serrano Pepper: 35
Salsa: 4

Arugula: 145
Romaine: 300
Collared Greens: 100
Mushrooms: 100
Radish: 100
Broccoli: 100
Cauliflower: 100
Avocado: 140
Extra Virgin Olive Oil: 5
Fish Oil: .5
